from playwright.sync_api import Page, Playwright, sync_playwright, expect
from time import sleep
import re


def delivery_zones_verification(page: Page):

    page.get_by_role("tab", name="Зоны доставки").click()
    page.locator(".sidebar_toggle").click()
    page.locator(".sidebar_toggle").click()
    page.get_by_placeholder("Выберите город").click()
    page.get_by_text("Алматы").click()
    sleep(2)
    page.get_by_role("link", name="Новая зона Создать новую зону").click()
    page.locator("#deliveryZonesMap").get_by_role("button").click()
    page.get_by_role("link", name="Отмена").click()
    page.get_by_role("link", name="Новая зона Создать новую зону").click()
    page.mouse.click(1000, 500)
    sleep(0.2)
    page.mouse.click(1000, 750)
    sleep(0.2)
    page.mouse.click(1100, 650)
    sleep(0.2)
    page.get_by_role("link", name="Удалить последнюю точку").click()
    sleep(0.2)
    page.mouse.click(1100, 650)
    sleep(0.2)
    page.mouse.click(1100, 600)
    sleep(0.2)
    page.get_by_role("link", name="Завершите редактирование").click()
    sleep(0.2)
    page.get_by_role("button", name="Удалить").click()
    page.get_by_role("link", name="Новая зона Создать новую зону").click()
    sleep(0.2)
    page.mouse.click(1000, 500)
    sleep(0.2)
    page.mouse.click(1000, 750)
    sleep(0.2)
    page.mouse.click(1100, 650)
    sleep(0.2)
    page.get_by_role("link", name="Завершите редактирование").click()
    page.get_by_placeholder("Название").fill("Желтый")
    page.locator(".css-10zey5s > span").first.click()
    page.locator("div:nth-child(5) > .css-10zey5s > span").click()
    page.get_by_role("button", name="Сохранить").click()
    page.get_by_role("row", name="Желтый").locator("div").first.click()
    page.get_by_role("button", name="Прикрепить курьера").click()
    page.get_by_label("​", exact=True).click()
    page.get_by_label("Ель На дереве").check()
    page.get_by_role("button", name="ОК").click()
    page.get_by_role("button", name="Прикрепить").click()
    page.get_by_role("button", name="Сбросить зону").click()
    page.get_by_role("button", name="Нет, не удалять").click()
    page.get_by_role("button", name="Сбросить зону").click()
    page.get_by_role("button", name="Да, удалить").click()

    print("Зоны доставки GOOD")
    sleep(1)
